export const CHANGE_EDIT_STATUS_CLASS= 'CHANGE_EDIT_STATUS_CLASS'
export const  FETCH_DATABASE_FEATURED_PRODUCTS = 'FETCH_DATABASE_FEATURED_PRODUCTS'
export const  FETCH_DATABASE_ALL_PRODUCTS = 'FETCH_DATABASE_ALL_PRODUCTS'
export const  GET_PRICE_FILTER = 'GET_PRICE_FILTER'
